# Specify an image with Node.js
image: node:18

# Define caching to speed up pipeline execution
cache:
  paths:
    - node_modules/

# Define the stages in the pipeline
stages:
  - install
  - build
  - deploy

# Install dependencies stage
install_dependencies:
  stage: install
  script:
    - npm ci

# Build the Next.js project
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next

# Deployment stage
deploy_production:
  stage: deploy
  script:
    - echo "Deploying to production..."
    # Add your deployment commands here
  only:
    - main # Deploy only on the main branch
